### ISSUE TITLE
Bug: Currently it is not possible to delete or update content with user progress data

### ISSUE THREAD

**Issue by myluki2000** [IT-REX-Platform/content_service#33]
## Description
It needs to be possible to delete or update content with user progress data.

## Acceptance criteria

- [ ] bug fixed

**Comment by PaulBredl** [comment]
@LG1401 Die Karte nehm ich noch in Angriff

**Comment by PaulBredl** [comment]
I just wasted four hours on this, still don't understand why it happens. Every workaround other way of doing failed so for now I just gave up.

**Comment by PaulBredl** [comment]
@LG1401 I will probably move it back to the backlog
